### ISSUE TITLE
Do it works with sockets?

### ISSUE THREAD

**Issue by jotae1e** [danielrataj/sails-hook-prometheus#1]
```
verbose: verbo: Interpreting socket.io message as VR (virtual request) to "put /api/v1/login"...
silly:      : Handling virtual request :: Running virtual querystring parser...
silly:      : Handling virtual request :: Running virtual body parser...
silly:      : Handling virtual request :: Running final "error" handler...
error: error: Sending 500 ("Server Error") response:
 TypeError: Cannot read property 'statusCode' of undefined
    at all /* (/certifirm/SailsBE_dev/node_modules/sails-hook-prometheus/src/index.js:43:36)
    at routeTargetFnWrapper (/certifirm/SailsBE_dev/node_modules/sails/lib/router/bind.js:392:9)
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
    at next (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:109:3)
    at handle (/certifirm/SailsBE_dev/node_modules/router/index.js:520:11)
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
    at /certifirm/SailsBE_dev/node_modules/router/index.js:296:22
    at param (/certifirm/SailsBE_dev/node_modules/router/index.js:373:14)
    at param (/certifirm/SailsBE_dev/node_modules/router/index.js:384:14)
    at Function.process_params (/certifirm/SailsBE_dev/node_modules/router/index.js:429:3)
    at next (/certifirm/SailsBE_dev/node_modules/router/index.js:290:10)
    at next (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:124:14)
    at logRequest (/certifirm/SailsBE_dev/node_modules/sails-hook-apianalytics/lib/private/log-request.middleware.js:109:10)
    at routeTargetFnWrapper (/certifirm/SailsBE_dev/node_modules/sails/lib/router/bind.js:392:9)
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
    at next (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:109:3)
    at handle (/certifirm/SailsBE_dev/node_modules/router/index.js:520:11)
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
    at /certifirm/SailsBE_dev/node_modules/router/index.js:296:22
    at param (/certifirm/SailsBE_dev/node_modules/router/index.js:373:14)
    at param (/certifirm/SailsBE_dev/node_modules/router/index.js:384:14)
    at Function.process_params (/certifirm/SailsBE_dev/node_modules/router/index.js:429:3)
    at next (/certifirm/SailsBE_dev/node_modules/router/index.js:290:10)
    at next (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:124:14)
    at fn (/certifirm/SailsBE_dev/api/hooks/custom/index.js:173:47)
    at routeTargetFnWrapper (/certifirm/SailsBE_dev/node_modules/sails/lib/router/bind.js:375:23)
    at /certifirm/SailsBE_dev/node_modules/sails/lib/router/bind.js:455:14
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
    at next (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/certifirm/SailsBE_dev/node_modules/router/lib/route.js:109:3)
    at handle (/certifirm/SailsBE_dev/node_modules/router/index.js:520:11)
    at Layer.handle [as handle_request] (/certifirm/SailsBE_dev/node_modules/router/lib/layer.js:93:5)
```

**Comment by danielrataj** [comment]
Hi, I'll check it out and get to you later. Thank you for letting me know.

**Comment by danielrataj** [comment]
Can you try newest version? I added option to enable/disable socket endpoint from being logged. It is disabled by default.

**Comment by jotae1e** [comment]
Well.  Sorry for my English.  Now it's working well but with the statusCode equals to 0 always.  I don't know why because sockets responds with an statusCode too.

I put this in sails:

```
module.exports.prometheus = {
  sockets: {
    enabled: true
  }
};
```
And this in prometheus.
  ```
- job_name: 'sails'
    static_configs:
      schema: https
      - targets: ['localhost:8081']
```

**Comment by danielrataj** [comment]
I released a new version that takes status code from response as well. However the 0 status is always logged.

**Comment by jotae1e** [comment]
Ok.  I will test this evening, because I am in the middle of a release.

On the other hand, can you tell me if you use grafana to see the results?  And If you use it, can you suggest what kind of graph are you using.

Thanks in advance.

**Comment by danielrataj** [comment]
We're using Grafana in our company. But the graphs and all related queries are provided by our dev-ops department. So I can't assist you in this case.
Thank you.
